### ISSUE TITLE
Bugs in Makefiles

### ISSUE THREAD

**Issue by kemonats** [phoenix-rtos/libphoenix#39]
1. Makefile:
line 22 unnecessary semicolon
is 
```bash
SED = sed;
```
should be
```bash
SED = sed
```

2.  string/Makefile:
line 15
is
```bash
%/errno.list: /usr/local/include/phoenix/errno.h include/errno.h
```
should be
```bash
%/errno.list: include/errno.h
```
I sent a pull request.

**Comment by agkaminski** [comment]
Fixed in d1eb669a04dd5420a03f0f82ac80ce6594dc0678
