### ISSUE TITLE
No optimization for armv7m

### ISSUE THREAD

**Issue by kemonats** [phoenix-rtos/libphoenix#47]
I noticed that there is no optimization for armv7m3, m4, m7.
Previously it was set to O2

**Comment by agkaminski** [comment]
It is enabled in phoenix-rtos-build makefile (which is included by libphoenix)

https://github.com/phoenix-rtos/phoenix-rtos-build/blob/f4f07e8e887ae11809f7ba7950e77bb1cf385aa0/Makefile.armv7#L19
