### ISSUE TITLE
Comparison of asm and c code size

### ISSUE THREAD

**Issue by kemonats** [phoenix-rtos/libphoenix#48]
I did a comparison of the size of the code generated for functions written using inline assembly and written in c.
```
gcc 7.1.1

armv7a7-imx6ull
            asm     c       diff
memcmp      32      26      12
strcmp      2e      28      6
strcpy      1c      14      8
strlen      14      10      4
strncmp     3a      2e      12
strncpy     3a      22      24
strnlen     1a      12      8

arm7m3-stm32l152xd
            asm     c       diff
memcmp      34      40      -12
strcmp      30      2c      4
strcpy      1e      14      10
strlen      14      14      0
strncmp     3c      4c      -16
strncpy     3c      3a      2
strnlen     1a      24      -10

asm and c - numbers as hex
diff - numbers as dec
```
As you can see above, in case of armv7a7 (-Os flag) the code in c takes less bytes than the code in assembler.
In the case of armv7m3 (flag -O2) this is different.

Why use assembler where the compiler does it better?

**Comment by agkaminski** [comment]
There are many goals of optimalization. Minimizing code footprint is one of them. Other goal is speed of execution. I would not say "compiler does it better" by comparing only one characteristic of the code. To say which one is better, we would need to perform performance benchmarks (for various dataset lengths).

For example - memcpy implementation has bigger footprint, for sure. But it includes some optimalizations, which compiler wouldn't be allowed to make (copying word by word, not byte by byte).

**Comment by kemonats** [comment]
I showed only those functions that are in both asmebler and c and operate on bytes.
My intention was to show that maybe the function code written in inline assembly is not the best and the algorithm should be changed.
the simplest example

disasembler
```
asm:
00000000 <strlen>:
   0:   2300            movs    r3, #0
   2:   5cc1            ldrb    r1, [r0, r3]
   4:   f103 0301       add.w   r3, r3, #1
   8:   2900            cmp     r1, #0
   a:   d1fa            bne.n   2 <strlen+0x2>
   c:   f1a3 0301       sub.w   r3, r3, #1
  10:   4618            mov     r0, r3
  12:   4770            bx      lr

c:
00000000 <strlen>:
   0:   4602            mov     r2, r0
   2:   4603            mov     r3, r0
   4:   1a98            subs    r0, r3, r2
   6:   f813 1b01       ldrb.w  r1, [r3], #1
   a:   2900            cmp     r1, #0
   c:   d1fa            bne.n   4 <t_strlen+0x4>
   e:   4770            bx      lr
```
It can be seen that the loop execution speed will be the same in both cases, but the code size of the whole function is 4 bytes smaller.
Looking at the code of other functions you can see where the difference is.

**Comment by agkaminski** [comment]
Ok, you have a point here. I agree it is unecessary to write str* functions in asm. But I think memcmp can be optimized beyond naive implementation.

We provide generic str* functions written in C. It is easy to fall back to them - it's a matter of deleting per arch implementation of these functions.

**Comment by kemonats** [comment]
It is also interesting how big the difference is when using different optimization methods.
e.g. `memcmp` size as hex
```
a7 -Os 26
m3 -O2 40
```
What is the reason for using different optimizations?
Maybe -Os is better for ARM.

The same situation is probably in the kernel.
What is the purpose of using the str * and mem * functions in inline kernel?

**Comment by agkaminski** [comment]
> What is the reason for using different optimizations?
We needed ARM target to fit on small OCRAM during first phase of booting. Now there's no real reason for -Os.

> What is the purpose of using the str * and mem * functions as inline in kernel?
We preffer performance over binary size in kernel.

**Comment by kemonats** [comment]
Does using inline significantly increase performance?
For i386 where arguments are passed through the stack, probably yes, but in ARM where arguments are passed through registers?
In addition, these functions are written in extended assembler.
This means that the compiler cannot optimize these functions.

Why different flags are used in lib and kernel for compilation.
```
         kernel lib
armv7a7  -Og    -Os
armv7m3  -Os    -O2
```

Regarding -g flag.
I meant that if `DEBUG=1` -g in `CFAGS` occurs twice
```
TARGET=armv7m7-imxrt105x
DEBUG=1
CFLAGS=-I/home/.../_build/armv7m7-imxrt105x/include/ -Og -g -Wall -Wstrict-prototypes -g -I -nostartfiles -nostdlib -mcpu=cortex-m7 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mthumb -fomit-frame-pointer -ffreestanding -mno-unaligned-access -fpic -fpie -msingle-pic-base -mno-pic-data-is-text-relative -DNOMMU -fdata-sections -ffunction-sections
```

**Comment by pawelpisarczyk** [comment]
Guys, what should we do with this issue?

**Comment by agkaminski** [comment]
IMHO we should do universal implementations in C (with word copying optimalization). As kemonats shown, nowadays handwritten assembly offers little to no advantage.

**Comment by pawelpisarczyk** [comment]
I don't agree with such opinion. I some cases this could be true in some cases not. It depends. Thx for interesting discussion :) So, I close this issue.
