### ISSUE TITLE
Unaligned pointer value warnings in armv7m7-imxrt when using gcc 9.3.0

### ISSUE THREAD

**Issue by Cinek28** [phoenix-rtos/libphoenix#53]
New warnings appear on build:
-> warning: taking address of packed member of 'struct _flash_context_t' may result in an unaligned pointer value [-Waddress-of-packed-member]
-> warning: taking address of packed member of 'struct _chunk_t' may result in an unaligned pointer value [-Waddress-of-packed-member]

from:
-> flashdrv.h
-> malloc_dl.c

**Comment by gerard5** [comment]
Looks resolved in the meantime (closing the issue). Tried to force error/warning by applying explicit `-Waddress-of-packed-member` flag no such warning appeared for any of the source files, test was conducted using:
```
Using built-in specs.
COLLECT_GCC=/opt/phoenix/arm-phoenix/bin/arm-phoenix-gcc
COLLECT_LTO_WRAPPER=/opt/phoenix-new/arm-phoenix/bin/../libexec/gcc/arm-phoenix/9.3.0/lto-wrapper
Target: arm-phoenix
Configured with: ../configure --target=arm-phoenix --prefix=/opt/phoenix/arm-phoenix --with-sysroot=/opt/phoenix/arm-phoenix/arm-phoenix --enable-languages=c,c++ --with-newlib --with-headers=yes --disable-tls --enable-initfini-array --disable-decimal-float --disable-libquadmath --disable-libssp --disable-nls
Thread model: single
gcc version 9.3.0 (GCC) 
```
Toolchain build on 04/02/2022.
