### ISSUE TITLE
getopt() behaviour implicitly conforms to POSIX

### ISSUE THREAD

**Issue by MaciejPurski** [phoenix-rtos/libphoenix#62]
Default behaviour for GNU getopt(), which is most popular, is to permute arguments, so that non-option (not starting with '-') arguments are moved to the end of argv array. Currently we conform to legacy POSIX implementation, which stops arguments parsing as soon as the first non-option argument is found. By default, as described in Linux man, POSIX behaviour should be enabled explicitly by setting environmental variable POSIXLY_CORRECT or prepending optstring with '+' char. It causes different than expected behaviour of some programs and forces user to strictly follow commands options order. For example when calling busybox `ls` command `ls bin -l`, option `-l` is treated as a path name.

**Comment by pawelpisarczyk** [comment]
I think that we should conform to GNU/Linux. This is not what I personally like, but there is a lot of open-source which uses GNU/Linux semantics rather then POSIX.
